FROM amd64/amazoncorretto:17
WORKDIR /app
COPY ./build/libs/wefresh-server-0.0.1-SNAPSHOT.jar /app/WEFRESH.jar
CMD ["java", "-Duser.timezone=Asia/Seoul", "-jar", "-Dspring.profiles.active=dev", "WEFRESH.jar"]