name: CI

on:
  pull_request:
    branches: [ "develop" ]

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: '17'

      - name: Cache Gradle dependencies
        uses: actions/cache@v3
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - name: Create application-dev.yml
        run: |
          mkdir -p ./src/main/resources
          echo "${{ secrets.APPLICATION_DEV }}" > ./src/main/resources/application-dev.yml
          cat ./src/main/resources/application-dev.yml
        shell: bash

      - name: Build
        run: |
          chmod +x gradlew
          ./gradlew build -x test
        shell: bash