name: develop-CD

on:
  push:
    branches: [ "develop" ]

jobs:
  ci:
    runs-on: ubuntu-22.04
    env:
      working-directory: .

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: '17'

      - name: Create application-dev.yml
        run: |
          mkdir -p ./src/main/resources
          echo "${{ secrets.APPLICATION_DEV }}" > ./src/main/resources/application-dev.yml
          cat ./src/main/resources/application-dev.yml
        shell: bash

      - name: Build Project
        run: |
          chmod +x gradlew
          ./gradlew build -x test
        shell: bash

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2.9.1

      - name: Docker Hub Login
        uses: docker/login-action@v2.2.0
        with:
          username: ${{ secrets.DOCKER_LOGIN_USERNAME }}
          password: ${{ secrets.DOCKER_LOGIN_ACCESSTOKEN }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile-dev
          push: true
          tags: ${{ secrets.DOCKER_LOGIN_USERNAME }}/${{ secrets.DEV_REPONAME }}:latest

  cd:
    needs: ci
    runs-on: ubuntu-22.04

    steps:
      - name: Deploy to Development Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DEV_EC2_IP }}
          username: ${{ secrets.DEV_EC2_USER }}
          key: ${{ secrets.DEV_EC2_KEY }}
          script: |
            cd ~
            ./deploy.sh